import json

f = open('teams.txt')
f2 = open('teams2.txt')

teamsstr = """[
 {
   "Payment": "Payment",
   "Team name": "Team name",
   "Team ID": "Team ID",
   "School": "School",
   "Member 1": "Member 1",
   "Member 2": "Member 2",
   "Member 3": "Member 3",
   "Member 4": "Member 4",
   "Proctor": "Proctor:",
   "Room Number": "Room :",
   "Finalized": "Finalized?",
   "Runner": "Runner:",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "Clarke A",
   "Team ID": "005A",
   "School": "Jonas Clarke Middle School",
   "Member 1": "Alex Li",
   "Member 2": "Ben Epstein",
   "Member 3": "Linda Chen",
   "Member 4": "Kathy Xue",
   "Proctor": "Benjamin Wright",
   "Room Number": "5",
   "Finalized": "Yes",
   "Runner": "James",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "Diamond School A",
   "Team ID": "005B",
   "School": "Diamond Middle School",
   "Member 1": "Jeremy Flemming",
   "Member 2": "Richard Chen",
   "Member 3": "Kristina Wong",
   "Member 4": "Bryce Zhang",
   "Proctor": "Benjamin Wright",
   "Room Number": "5",
   "Finalized": "Yes",
   "Runner": "James",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "Clarke B",
   "Team ID": "006A",
   "School": "Jonas Clarke Middle School",
   "Member 1": "Euhan Kim",
   "Member 2": "Sammy Charney",
   "Member 3": "Jeff Lin",
   "Member 4": "Arthur Hu",
   "Proctor": "Brian Liu",
   "Room Number": "6",
   "Finalized": "Yes",
   "Runner": "James",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "Diamond School B",
   "Team ID": "006B",
   "School": "Diamond Middle School",
   "Member 1": "Tianyi Yang",
   "Member 2": "Armaan Tipirneni",
   "Member 3": "Anthony Zhao",
   "Member 4": "Alexander Peng",
   "Proctor": "Brian Liu",
   "Room Number": "6",
   "Finalized": "Yes",
   "Runner": "James",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "Clarke C",
   "Team ID": "007A",
   "School": "Jonas Clarke Middle School",
   "Member 1": "Fangze Tian",
   "Member 2": "Kira Tang",
   "Member 3": "Jocelyn Hsieh",
   "Member 4": "Alex Tang",
   "Proctor": "Maxwell Wang",
   "Room Number": "7",
   "Finalized": "Yes",
   "Runner": "James",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "Diamond School C",
   "Team ID": "007B",
   "School": "Diamond Middle School",
   "Member 1": "VIctoria Yuan",
   "Member 2": "Julian Han",
   "Member 3": "Brian Yu",
   "Member 4": "Matthew Wang",
   "Proctor": "Maxwell Wang",
   "Room Number": "7",
   "Finalized": "Yes",
   "Runner": "James",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "Clarke D",
   "Team ID": "008A",
   "School": "Jonas Clarke Middle School",
   "Member 1": "Kunal Kapoor",
   "Member 2": "Aahan Mehra",
   "Member 3": "Anna Zhang",
   "Member 4": "Charlie Chen",
   "Proctor": "Victor Luo",
   "Room Number": "8",
   "Finalized": "Yes",
   "Runner": "James",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "It's 5 year old simple",
   "Team ID": "008B",
   "School": "Lexington Diamond Middle School",
   "Member 1": "Surya Meiyappan",
   "Member 2": "William Yang",
   "Member 3": "Matt Berhe",
   "Member 4": "Jacob Epstein",
   "Proctor": "Victor Luo",
   "Room Number": "8",
   "Finalized": "Yes",
   "Runner": "James",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "Doherty Middle School",
   "Team ID": "009A",
   "School": "Doherty Middle School",
   "Member 1": "Christina Li",
   "Member 2": "Steven Zhang",
   "Member 3": "Kaylee Ji",
   "Member 4": "Emily Chen",
   "Proctor": "Adam Bertelli",
   "Room Number": "9",
   "Finalized": "Yes",
   "Runner": "James",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "LYCAL",
   "Team ID": "009B",
   "School": "Lexington Youth Center for Asian Learning",
   "Member 1": "Eric Teng Tu",
   "Member 2": "Richard Chen",
   "Member 3": "Christopher Ye",
   "Member 4": "Ivy Zhang",
   "Proctor": "Adam Bertelli",
   "Room Number": "9",
   "Finalized": "Yes",
   "Runner": "James",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "Four Seasons",
   "Team ID": "021A",
   "School": "Four Seasons Education",
   "Member 1": "Changhao Lin",
   "Member 2": "Yixi Chen",
   "Member 3": "Xinle Yu",
   "Member 4": "Yan Weng",
   "Proctor": "Chris Hambacher",
   "Room Number": "21",
   "Finalized": "Yes",
   "Runner": "James",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "Pike School A",
   "Team ID": "021B",
   "School": "The Pike School",
   "Member 1": "Kris Aziabor",
   "Member 2": "Arnav Bhakta",
   "Member 3": "Jay Aziabor",
   "Member 4": "Adam Jac",
   "Proctor": "Chris Hambacher",
   "Room Number": "21",
   "Finalized": "Yes",
   "Runner": "James",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "Shibei Middle School",
   "Team ID": "022A",
   "School": "Shibei Middle School",
   "Member 1": "Peiqing Chen",
   "Member 2": "Meng Sun",
   "Member 3": "Zhefei Cao",
   "Member 4": "Yihua Sun",
   "Proctor": "Isaac Browne",
   "Room Number": "22",
   "Finalized": "Yes",
   "Runner": "James",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "Pike School B",
   "Team ID": "022B",
   "School": "The Pike School",
   "Member 1": "Alexander Lho",
   "Member 2": "Stephanie Yang",
   "Member 3": "Jerry Shu",
   "Member 4": "Chen-chen Song",
   "Proctor": "Isaac Browne",
   "Room Number": "22",
   "Finalized": "Yes",
   "Runner": "James",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "SFLS 1",
   "Team ID": "025A",
   "School": "Shanghai Foreign Language School",
   "Member 1": "Jiayi Wang",
   "Member 2": "Yixiao Huang",
   "Member 3": "Hanqing Li",
   "Member 4": "Zhongyu Huang",
   "Proctor": "Brian Bae",
   "Room Number": "25",
   "Finalized": "Yes",
   "Runner": "James",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "dx",
   "Team ID": "025B",
   "School": "Boston Latin School",
   "Member 1": "Ronak",
   "Member 2": "Eric Cheung",
   "Member 3": "Raymond",
   "Member 4": "Ruth Shiferaw",
   "Proctor": "Brian Bae",
   "Room Number": "25",
   "Finalized": "Yes",
   "Runner": "James",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "SFLS 2",
   "Team ID": "027A",
   "School": "Shanghai Foreign Language School",
   "Member 1": "Yuchen Yang",
   "Member 2": "Junkai Wang",
   "Member 3": "Yurou Liu",
   "Member 4": "Yuhe Huang",
   "Proctor": "Jinpyo Hong",
   "Room Number": "27",
   "Finalized": "Yes",
   "Runner": "James",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "dy",
   "Team ID": "027B",
   "School": "Boston Latin School",
   "Member 1": "Alice Zhang",
   "Member 2": "John Lin",
   "Member 3": "Albert Zhang",
   "Member 4": "Julianna Zhao",
   "Proctor": "Jinpyo Hong",
   "Room Number": "27",
   "Finalized": "Yes",
   "Runner": "James",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "SFLS 3",
   "Team ID": "029A",
   "School": "Shanghai Foreign Language School",
   "Member 1": "Yiwen Li",
   "Member 2": "Jialin Zuo",
   "Member 3": "Jingxian Li",
   "Member 4": "Yihong Gu",
   "Proctor": "William Park",
   "Room Number": "29",
   "Finalized": "Yes",
   "Runner": "Kristy",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "Day One",
   "Team ID": "029B",
   "School": "FA Day Middle School",
   "Member 1": "Charles Li",
   "Member 2": "Jason Jiang",
   "Member 3": "Eric Yu",
   "Member 4": "Steven Gao",
   "Proctor": "William Park",
   "Room Number": "29",
   "Finalized": "Yes",
   "Runner": "Kristy",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "SFLS 4",
   "Team ID": "030A",
   "School": "Shanghai Foreign Language School",
   "Member 1": "Xinyu Zhang",
   "Member 2": "Mingjiu Zhao",
   "Member 3": "Yingqi Liu",
   "Member 4": "Yangyi Gao",
   "Proctor": "James Wang",
   "Room Number": "30",
   "Finalized": "Yes",
   "Runner": "Kristy",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "Day Two",
   "Team ID": "030B",
   "School": "FA Day Middle School",
   "Member 1": "Ryan Shu",
   "Member 2": "Jacob Ye",
   "Member 3": "David Li",
   "Member 4": "Thomas Wang",
   "Proctor": "James Wang",
   "Room Number": "30",
   "Finalized": "Yes",
   "Runner": "Kristy",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "Beijing 1",
   "Team ID": "102A",
   "School": "Affiliated HS to Peking Univ.",
   "Member 1": "Ze Fan",
   "Member 2": "Tianyi Lu",
   "Member 3": "Xike Song",
   "Member 4": "Yuhan Wang",
   "Proctor": "Zac Feng",
   "Room Number": "102",
   "Finalized": "Yes",
   "Runner": "Kristy",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "AMSA Blue",
   "Team ID": "102B",
   "School": "Advanced Math and Science Academy",
   "Member 1": "Sruthi Kurada",
   "Member 2": "Samuel David",
   "Member 3": "Matt Young",
   "Member 4": "Shane Ferrante",
   "Proctor": "Zac Feng",
   "Room Number": "102",
   "Finalized": "Yes",
   "Runner": "Kristy",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "Beijing 2",
   "Team ID": "104A",
   "School": "Affiliated HS to Peking Univ.",
   "Member 1": "Chenui Jim",
   "Member 2": "Jinhui Cao",
   "Member 3": "Yukun Guan",
   "Member 4": "Hanlin Gao",
   "Proctor": "Evan Xiang",
   "Room Number": "104",
   "Finalized": "Yes",
   "Runner": "Kristy",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "AMSA Red",
   "Team ID": "104B",
   "School": "Advanced Math and Science Academy",
   "Member 1": "Vikram Kaushik",
   "Member 2": "Ryan Young",
   "Member 3": "Krishna Purimetla",
   "Member 4": "Sidhant Roymoulik",
   "Proctor": "Evan Xiang",
   "Room Number": "104",
   "Finalized": "Yes",
   "Runner": "Kristy",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "Beijing 3",
   "Team ID": "105A",
   "School": "Affiliated HS to Peking Univ.",
   "Member 1": "Liyuan Liu",
   "Member 2": "Zhuoqi Wu",
   "Member 3": "Sixue Li",
   "Member 4": "Bati Li",
   "Proctor": "Jenny Yang",
   "Room Number": "105",
   "Finalized": "Yes",
   "Runner": "Kristy",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "AMSA Gold",
   "Team ID": "105B",
   "School": "Advanced Math and Science Academy",
   "Member 1": "Kazuya Erdos",
   "Member 2": "Kavika Krishnan",
   "Member 3": "Nikhil Rao",
   "Member 4": "Griffin Coyle",
   "Proctor": "Jenny Yang",
   "Room Number": "105",
   "Finalized": "Yes",
   "Runner": "Kristy",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "Beijing No. 4 1",
   "Team ID": "106A",
   "School": "Beijing No. 4 MS",
   "Member 1": "Jiahui Zhang",
   "Member 2": "Jiaming Xu",
   "Member 3": "Ruoyi Liu",
   "Member 4": "Dingchen Zhang",
   "Proctor": "Angelina Zhang",
   "Room Number": "106",
   "Finalized": "Yes",
   "Runner": "Kristy",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "Rectory Wolves",
   "Team ID": "106B",
   "School": "The Rectory School",
   "Member 1": "Betty Xu",
   "Member 2": "Paula Jiang",
   "Member 3": "Sunny Chen",
   "Member 4": "Jonathan Chen",
   "Proctor": "Angelina Zhang",
   "Room Number": "106",
   "Finalized": "Yes",
   "Runner": "Kristy",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "Beijing No. 4 2",
   "Team ID": "107A",
   "School": "Beijing No. 4 MS",
   "Member 1": "Bingshuai Fu",
   "Member 2": "Heyang An",
   "Member 3": "Xiaoyun Guo",
   "Member 4": "Buoyu Xiao",
   "Proctor": "Anjali Gupta",
   "Room Number": "107",
   "Finalized": "Yes",
   "Runner": "Kristy",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "Rectory Black Wolves",
   "Team ID": "107B",
   "School": "The Rectory School",
   "Member 1": "Angelina Qian",
   "Member 2": "Insel Lee",
   "Member 3": "Jonathan Hui",
   "Member 4": "David Liu",
   "Proctor": "Anjali Gupta",
   "Room Number": "107",
   "Finalized": "Yes",
   "Runner": "Kristy",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "Beijing No. 4 3",
   "Team ID": "108A",
   "School": "Beijing No. 4 MS",
   "Member 1": "Juntong Liu",
   "Member 2": "Danqing Chen",
   "Member 3": "Junchi Li",
   "Member 4": "Xingzao Jiang",
   "Proctor": "Mahdi Hamad",
   "Room Number": "108",
   "Finalized": "Yes",
   "Runner": "Kristy",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "Rectory Silver Wolves",
   "Team ID": "108B",
   "School": "The Rectory School",
   "Member 1": "Leo Wu",
   "Member 2": "Catherine Xie",
   "Member 3": "Tina Wang",
   "Member 4": "Kevin Zhang",
   "Proctor": "Mahdi Hamad",
   "Room Number": "108",
   "Finalized": "Yes",
   "Runner": "Kristy",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "Nanjing",
   "Team ID": "109A",
   "School": "Nanjing",
   "Member 1": "Wanhe Zhu",
   "Member 2": "Huishen Peng",
   "Member 3": "Yixun Xu",
   "Member 4": "Jiaheng Han",
   "Proctor": "Elizabeth Yang",
   "Room Number": "109",
   "Finalized": "Yes",
   "Runner": "Stephen",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "Maniac",
   "Team ID": "109B",
   "School": "Andover",
   "Member 1": "Alicia Li",
   "Member 2": "Evan Huang",
   "Member 3": "Alex Wu",
   "Member 4": "Isabel Tu",
   "Proctor": "Elizabeth Yang",
   "Room Number": "109",
   "Finalized": "Yes",
   "Runner": "Stephen",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "Tsinghua 1",
   "Team ID": "119A",
   "School": "HS attached to Tsinghua Univ.",
   "Member 1": "Xinyi Xiong",
   "Member 2": "Yumeng Wang",
   "Member 3": "Yiran Cao",
   "Member 4": "Beining Zhou",
   "Proctor": "Solon James",
   "Room Number": "119",
   "Finalized": "Yes",
   "Runner": "Stephen",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "Bergen County Academies - Tyr",
   "Team ID": "119B",
   "School": "Bergen County Academies",
   "Member 1": "Debra Boutom",
   "Member 2": "Katherine Vandermel",
   "Member 3": "Kevin Li",
   "Member 4": "Johnathan Wong",
   "Proctor": "Solon James",
   "Room Number": "119",
   "Finalized": "Yes",
   "Runner": "Stephen",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "Tsinghua 2",
   "Team ID": "121A",
   "School": "HS attached to Tsinghua Univ.",
   "Member 1": "Jiangshan Gao",
   "Member 2": "Feiyang Yang",
   "Member 3": "Xinyue Zhang",
   "Member 4": "Zixi Wang",
   "Proctor": "Junze Ye",
   "Room Number": "121",
   "Finalized": "Yes",
   "Runner": "Stephen",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "Bergen County Academies - Loki",
   "Team ID": "121B",
   "School": "Bergen County Academies",
   "Member 1": "Marvin Mao",
   "Member 2": "Benjamin Liu",
   "Member 3": "Michelle Tan",
   "Member 4": "Kishan Bava",
   "Proctor": "Junze Ye",
   "Room Number": "121",
   "Finalized": "Yes",
   "Runner": "Stephen",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "Tsinghua 3",
   "Team ID": "122A",
   "School": "HS attached to Tsinghua Univ.",
   "Member 1": "Shiqi Huang",
   "Member 2": "Yinzhen Du",
   "Member 3": "Shuang Wu",
   "Member 4": "Xiaosen Sun",
   "Proctor": "Sanath Govindarajan",
   "Room Number": "122",
   "Finalized": "Yes",
   "Runner": "Stephen",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "Bergen County Academies - Sif",
   "Team ID": "122B",
   "School": "Bergen County Academies",
   "Member 1": "Jooeun Lee",
   "Member 2": "Julia Yul Kim",
   "Member 3": "Sophie Liu",
   "Member 4": "Linda Sun",
   "Proctor": "Sanath Govindarajan",
   "Room Number": "122",
   "Finalized": "Yes",
   "Runner": "Stephen",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "Renmin 1",
   "Team ID": "123A",
   "School": "HS Affiliated to Renmin Univ.",
   "Member 1": "Zhiqian Chen",
   "Member 2": "Yi Liang",
   "Member 3": "Yuzhou Yuan",
   "Member 4": "Jianan Xie",
   "Proctor": "Gautam Ramesh",
   "Room Number": "123",
   "Finalized": "Yes",
   "Runner": "Stephen",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "Bergen County Academies - Thor",
   "Team ID": "123B",
   "School": "Bergen County Academies",
   "Member 1": "Gregory Pylypovych",
   "Member 2": "Shrestha Hari",
   "Member 3": "Vincent Xu",
   "Member 4": "Lasal Mapitigama",
   "Proctor": "Gautam Ramesh",
   "Room Number": "123",
   "Finalized": "Yes",
   "Runner": "Stephen",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "Renmin 2",
   "Team ID": "125A",
   "School": "HS Affiliated to Renmin Univ.",
   "Member 1": "Yichen Xiao",
   "Member 2": "Peiqi Zhang",
   "Member 3": "Zijian Zhang",
   "Member 4": "Evan Ai",
   "Proctor": "Zoe Marshall",
   "Room Number": "125",
   "Finalized": "Yes",
   "Runner": "Stephen",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "Bergen County Academies - Ragnarok",
   "Team ID": "125B",
   "School": "Bergen County Academies",
   "Member 1": "Joseph Huang",
   "Member 2": "Jessica Lee",
   "Member 3": "Yuji Choi",
   "Member 4": "Michael Wong",
   "Proctor": "Zoe Marshall",
   "Room Number": "125",
   "Finalized": "Yes",
   "Runner": "Stephen",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "CCLS 1",
   "Team ID": "126A",
   "School": "Century Chinese Language School",
   "Member 1": "Eric Yang",
   "Member 2": "William Yue",
   "Member 3": "Andrew W. Lee",
   "Member 4": "Jason Tang",
   "Proctor": "Calvin Henaku",
   "Room Number": "126",
   "Finalized": "Yes",
   "Runner": "Stephen",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "Bergen County Academies - Odin",
   "Team ID": "126B",
   "School": "Bergen County Academies",
   "Member 1": "Vivian Tan",
   "Member 2": "Jongwon Jung",
   "Member 3": "Yunseo Choi",
   "Member 4": "Siwen Simon Sun",
   "Proctor": "Calvin Henaku",
   "Room Number": "126",
   "Finalized": "Yes",
   "Runner": "Stephen",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "CCLS 2",
   "Team ID": "127A",
   "School": "Century Chinese Language School",
   "Member 1": "Eric Zhang",
   "Member 2": "Sophia Tate",
   "Member 3": "Audrey Lin",
   "Member 4": "Emma Sun",
   "Proctor": "Tobi Abelmann",
   "Room Number": "127",
   "Finalized": "Yes",
   "Runner": "Stephen",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "Long Island Super",
   "Team ID": "127B",
   "School": "Jericho and Syosset Middle Schools",
   "Member 1": "Ethan Zhang",
   "Member 2": "Alex He",
   "Member 3": "William Hu",
   "Member 4": "Zhebin Zhao",
   "Proctor": "Tobi Abelmann",
   "Room Number": "127",
   "Finalized": "Yes",
   "Runner": "Stephen",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "CCLS 3",
   "Team ID": "128A",
   "School": "Century Chinese Language School",
   "Member 1": "Charlotte Wang",
   "Member 2": "Joshua Cheng",
   "Member 3": "Kenneth Wan",
   "Member 4": "Joshua Shen",
   "Proctor": "Dawson Byrd",
   "Room Number": "128",
   "Finalized": "Yes",
   "Runner": "Michael",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "Bancroft Bulldogs",
   "Team ID": "128B",
   "School": "Bancroft School",
   "Member 1": "Joshua Seiple",
   "Member 2": "Rory Chambers",
   "Member 3": "Kaia Outzen",
   "Member 4": "Yasha Barshteyn",
   "Proctor": "Dawson Byrd",
   "Room Number": "128",
   "Finalized": "Yes",
   "Runner": "Michael",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "WAW United",
   "Team ID": "206A",
   "School": "RJ Grey JHS; McCall Middle School; Blanchard Middle School",
   "Member 1": "Alexander Sun",
   "Member 2": "Eddie Wang",
   "Member 3": "William Sun",
   "Member 4": "Matthew Ding",
   "Proctor": "Queenie Zhang",
   "Room Number": "206",
   "Finalized": "Yes",
   "Runner": "Michael",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "Pi In The Sky",
   "Team ID": "206B",
   "School": "Timothy Edwards Middle School",
   "Member 1": "Ishan Kumar",
   "Member 2": "Aryan Kalia",
   "Member 3": "Pranav Ramesh",
   "Member 4": "Keshav Ramesh",
   "Proctor": "Queenie Zhang",
   "Room Number": "206",
   "Finalized": "Yes",
   "Runner": "Michael",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "Nobles",
   "Team ID": "207A",
   "School": "Noble and Greenough School",
   "Member 1": "Daniel Wang",
   "Member 2": "Justin Qin",
   "Member 3": "Lucy Cai",
   "Member 4": "Claire Mao",
   "Proctor": "Richard Chen",
   "Room Number": "207",
   "Finalized": "Yes",
   "Runner": "Michael",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "RJ Grey",
   "Team ID": "207B",
   "School": "Raymond J Grey Junior High School",
   "Member 1": "Anuj Sakarda",
   "Member 2": "Jerry Tan",
   "Member 3": "Poonam Sahoo",
   "Member 4": "Justin Shan",
   "Proctor": "Richard Chen",
   "Room Number": "207",
   "Finalized": "Yes",
   "Runner": "Michael",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "Rock Math",
   "Team ID": "208A",
   "School": "LexingtonMath",
   "Member 1": "Robert Sheng",
   "Member 2": "Eddie Wei",
   "Member 3": "Kevin Guo",
   "Member 4": "Jianzhou Liu",
   "Proctor": "Daniel Li",
   "Room Number": "208",
   "Finalized": "Yes",
   "Runner": "Michael",
   "FIELD13": "",
   "FIELD14": ""
 },
 {
   "Payment": "",
   "Team name": "Wayland Math Team",
   "Team ID": "208B",
   "School": "Wayland Middle School",
   "Member 1": "Hannah Han",
   "Member 2": "Kevin Zhao",
   "Member 3": "June Kim",
   "Member 4": "Andrew Zhao",
   "Proctor": "Daniel Li",
   "Room Number": "208",
   "Finalized": "Yes",
   "Runner": "Michael",
   "FIELD13": "",
   "FIELD14": ""
 }
]"""
teams2str = """[{"school": "The Rectory School", "assigned_id": null, "combinable": true, "name": "Rectory Wolves", "members": [{"assigned_id": null, "name": "Betty Xu", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDT_oAJDA"}, {"assigned_id": null, "name": "Paula Jiang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDT_oAKDA"}, {"assigned_id": null, "name": "Sunny Chen", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgICNr50KDA"}, {"assigned_id": null, "name": "Jonathan Chen", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDT6p4LDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgMDk25MJDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgMC1_7EIDA", "deletable": false}, {"school": "Andover", "assigned_id": null, "combinable": true, "name": "Maniac", "members": [{"assigned_id": null, "name": "Alicia Li", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDioo4JDA"}, {"assigned_id": null, "name": "Evan Huang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCaopMKDA"}, {"assigned_id": null, "name": "Alex Wu", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCxn4MLDA"}, {"assigned_id": null, "name": "Isabel Tu", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMC1jZ4LDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgICV9ZsJDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgIDurMQIDA", "deletable": false}, {"school": "Bergen County Academies", "assigned_id": null, "combinable": true, "name": "Bergen County Academies - Thor", "members": [{"assigned_id": null, "name": "Vincent Xu", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCyhYQJDA"}, {"assigned_id": null, "name": "Gregory Pylypovych", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCNtYYJDA"}, {"assigned_id": null, "name": "Shrestha Hari", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCXg4QLDA"}, {"assigned_id": null, "name": "Lasal Mapitigama", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgIDt5pwLDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgICN84wJDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgMCSvs0IDA", "deletable": false}, {"school": "Bergen County Academies", "assigned_id": null, "combinable": true, "name": "Bergen County Academies - Ragnarok", "members": [{"assigned_id": null, "name": "Jessica Lee", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDakM4IDA"}, {"assigned_id": null, "name": "Joseph Hwang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCJ84QJDA"}, {"assigned_id": null, "name": "Yuji Choi", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDakI4LDA"}, {"assigned_id": null, "name": "Michael Wong", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgIDojpsLDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgICN84wJDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgMCSz9IIDA", "deletable": false}, {"school": "Shanghai Foreign Language School", "assigned_id": null, "combinable": true, "name": "SFLS 4", "members": [{"assigned_id": null, "name": "Yangyi Gao", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDy0YoJDA"}, {"assigned_id": null, "name": "Xinyu Zhang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDX8IwKDA"}, {"assigned_id": null, "name": "Mingjiu Zhao", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCeg5QKDA"}, {"assigned_id": null, "name": "Yingqi Liu", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgKDkuJsKDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgIDOnJwJDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgMD85NgIDA", "deletable": false}, {"school": "Bergen County Academies", "assigned_id": null, "combinable": true, "name": "Bergen County Academies - Loki", "members": [{"assigned_id": null, "name": "Kishan Bava", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgKDQyJ8JDA"}, {"assigned_id": null, "name": "Benjamin Liu", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDakM4JDA"}, {"assigned_id": null, "name": "MIchelle Tan", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCe0okLDA"}, {"assigned_id": null, "name": "Marvin Mao", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCepJALDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgICN84wJDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgMCaydsIDA", "deletable": false}, {"school": "The Rectory School", "assigned_id": null, "combinable": true, "name": "Rectory Black Wolves", "members": [{"assigned_id": null, "name": "Angelina Qian", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgICNr50JDA"}, {"assigned_id": null, "name": "Insel Lee", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDT6p4JDA"}, {"assigned_id": null, "name": "Jonathan Hui", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCS9IUKDA"}, {"assigned_id": null, "name": "David Liu", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCS6pQKDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgMDk25MJDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgMCXpIAJDA", "deletable": false}, {"school": "Four Seasons Education", "assigned_id": null, "combinable": true, "name": "Four Seasons", "members": [{"assigned_id": null, "name": "Yan Weng", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgKCQ-YYJDA"}, {"assigned_id": null, "name": "Xinle Yu", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgICtxYkKDA"}, {"assigned_id": null, "name": "Yixi Chen", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCJmpEKDA"}, {"assigned_id": null, "name": "Changhao Lin", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCXmZkKDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgIDOnJwJDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgMC8jYEJDA", "deletable": false}, {"school": "Jonas Clarke Middle School", "assigned_id": null, "combinable": true, "name": "Clarke C", "members": [{"assigned_id": null, "name": "Fangze Tian", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCz2IQKDA"}, {"assigned_id": null, "name": "Kira Tang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgICe3Y4KDA"}, {"assigned_id": null, "name": "Jocelyn Hsieh", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDu4ZcKDA"}, {"assigned_id": null, "name": "Alex Tang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMD1l50KDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgMCEzJAKDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgMDkrYIJDA", "deletable": false}, {"school": "Jonas Clarke Middle School", "assigned_id": null, "combinable": true, "name": "Clarke A", "members": [{"assigned_id": null, "name": "Alex Li", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgIDui8IIDA"}, {"assigned_id": null, "name": "Ben Epstein", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgIDNuMIIDA"}, {"assigned_id": null, "name": "Linda Chen", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDuhsYIDA"}, {"assigned_id": null, "name": "Kathy Xue", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDT9I8JDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgMCEzJAKDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgICcyIMJDA", "deletable": false}, {"school": "Bergen County Academies", "assigned_id": null, "combinable": true, "name": "Bergen County Academies - Odin", "members": [{"assigned_id": null, "name": "Vivian Tan", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgKDkuJsJDA"}, {"assigned_id": null, "name": "Yunseo Choi", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgIDo544KDA"}, {"assigned_id": null, "name": "Simon Sun", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDX8IwLDA"}, {"assigned_id": null, "name": "Jongwon Jung", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCeg5QLDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgICN84wJDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgMD1w4wJDA", "deletable": false}, {"school": "Boston Latin School", "assigned_id": null, "combinable": true, "name": "dy", "members": [{"assigned_id": null, "name": "Alice Zhang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgIC1oZwJDA"}, {"assigned_id": null, "name": "John Lin", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgIDwoI4LDA"}, {"assigned_id": null, "name": "Albert Zhang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDsj48LDA"}, {"assigned_id": null, "name": "Julianna Zhao", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgIDw1J8LDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgMCkvoAKDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgIDwoI4JDA", "deletable": false}, {"school": "The Sage School", "assigned_id": null, "combinable": true, "name": "Sage Blue", "members": [{"assigned_id": null, "name": "Oscar Capraro", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCatooJDA"}, {"assigned_id": null, "name": "Jacob Greenfield", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDTkJYKDA"}, {"assigned_id": null, "name": "Isaac Lau", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgICrsJwKDA"}, {"assigned_id": null, "name": "Achyuta Rajaram", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgICN0JELDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgMC1_5EKDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgMC1_5EJDA", "deletable": false}, {"school": "Century Chinese Language School", "assigned_id": null, "combinable": true, "name": "CCLS 3", "members": [{"assigned_id": null, "name": "Charlotte Wang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgICOrokKDA"}, {"assigned_id": null, "name": "Joshua Cheng", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgIDcg5kKDA"}, {"assigned_id": null, "name": "Kenneth Wan", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgICIppwKDA"}, {"assigned_id": null, "name": "Joshua Shen", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCIiZ4KDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgICQx4AKDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgMDc-ZMJDA", "deletable": false}, {"school": "HS attached to Tsinghua Univ.", "assigned_id": null, "combinable": true, "name": "Tsinghua 3", "members": [{"assigned_id": null, "name": "Shiqi Huang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDSu54KDA"}, {"assigned_id": null, "name": "Yinzhen Du", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgICt4M4KDA"}, {"assigned_id": null, "name": "SHUANG WU", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCXzogLDA"}, {"assigned_id": null, "name": "Xiaosen Sun", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCz8Z0LDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgID1qY8KDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgID19pYJDA", "deletable": false}, {"school": "Advanced Math and Science Academy Charter School", "assigned_id": null, "combinable": true, "name": "AMSA Blue", "members": [{"assigned_id": null, "name": "TBD 3", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDUkYUKDA"}, {"assigned_id": null, "name": "TBD 1", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgIDwhYkKDA"}, {"assigned_id": null, "name": "TBD 2", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDws4sKDA"}, {"assigned_id": null, "name": "TBD 4", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgIDwk5gKDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgMDsxYcKDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgICwu5cJDA", "deletable": false}, {"school": "Beijing No. 4 MS", "assigned_id": null, "combinable": true, "name": "Beijing No. 4 3", "members": [{"assigned_id": null, "name": "Juntong Liu", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCNiMIIDA"}, {"assigned_id": null, "name": "Danqing Chen", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgICt4M4IDA"}, {"assigned_id": null, "name": "JUNCHI LI", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDS8dYKDA"}, {"assigned_id": null, "name": "Xingzao Jiang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDuq58LDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgID1qY8KDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgIDLjpgJDA", "deletable": false}, {"school": "Gauss School of Mathematics", "assigned_id": null, "combinable": true, "name": "Golden Tigers", "members": [{"assigned_id": null, "name": "Kevin Liu", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgIDgwZwJDA"}, {"assigned_id": null, "name": "Stanley Jiang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgIDglYMKDA"}, {"assigned_id": null, "name": "Eric Yang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgICqopQKDA"}, {"assigned_id": null, "name": "Sean Liu", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgICquIULDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgIC2oIgJDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgICP6JgJDA", "deletable": false}, {"school": "Bromfield", "assigned_id": null, "combinable": true, "name": "Bromfield2", "members": [{"assigned_id": null, "name": "Sophia Zhou", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCu8pUKDA"}, {"assigned_id": null, "name": "Jason Qian", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgIDurMQKDA"}, "", ""], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgMCugJkKDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgMCugJkJDA", "deletable": false}, {"school": "HS Affiliated to Renmin Univ.", "assigned_id": null, "combinable": true, "name": "Renmin 1", "members": [{"assigned_id": null, "name": "Zhiqian Chen", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDVt8sIDA"}, {"assigned_id": null, "name": "Yi Liang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDItJkJDA"}, {"assigned_id": null, "name": "Yuzhou Yuan", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDCjsgJDA"}, {"assigned_id": null, "name": "Jianan Xie", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDCktEKDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgID1qY8KDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgMCOk5oJDA", "deletable": false}, {"school": "Westchester Area Math Circle", "assigned_id": null, "combinable": true, "name": "Westchester Area Math Circle B", "members": [{"assigned_id": null, "name": "Sumer Moudgill", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgIDslIkKDA"}, {"assigned_id": null, "name": "Brandon Yu", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgICzjZEKDA"}, {"assigned_id": null, "name": "Naved Azim", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDE1pIKDA"}, {"assigned_id": null, "name": "Anika Puri", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgICQtpYKDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgMCEmokKDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgIDP8poJDA", "deletable": false}, {"school": "Diamond Middle School", "assigned_id": null, "combinable": true, "name": "Diamond School B", "members": [{"assigned_id": null, "name": "Alexander Peng", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCemcUIDA"}, {"assigned_id": null, "name": "Armaan Tipirneni", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCeg9QIDA"}, {"assigned_id": null, "name": "Tianyi Yang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgKDkooYKDA"}, {"assigned_id": null, "name": "Anthony Zhao", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDJwp0KDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgICO5IEKDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgMD8w5wJDA", "deletable": false}, {"school": "Beijing No. 4 MS", "assigned_id": null, "combinable": true, "name": "Beijing No. 4 2", "members": [{"assigned_id": null, "name": "BINGSHUAI FU", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgKDgrcwIDA"}, {"assigned_id": null, "name": "Heyang An", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCzu9MIDA"}, {"assigned_id": null, "name": "Xiaoyan Guo", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgKDg5sQKDA"}, {"assigned_id": null, "name": "Buoyu Xiao", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDSgtoLDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgID1qY8KDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgMCM9p0JDA", "deletable": false}, {"school": "Bergen County Academies", "assigned_id": null, "combinable": true, "name": "Bergen County Academies - Heimdall", "members": [{"assigned_id": null, "name": "Michael (Zheng) Wu", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDa6oEJDA"}, {"assigned_id": null, "name": "Hyunkyu (Ben) Lee", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgKCwg4sJDA"}, {"assigned_id": null, "name": "Arosh De Silva", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDNhJ8JDA"}, {"assigned_id": null, "name": "Michael Yin", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgKCi4YEKDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgICN84wJDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgIDui8IJDA", "deletable": false}, {"school": "Bancroft School", "assigned_id": null, "combinable": true, "name": "Bancroft Bulldogs", "members": [{"assigned_id": null, "name": "Yasha Barshteyn", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgKCk74oKDA"}, {"assigned_id": null, "name": "Peter Wixted", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDJuIwKDA"}, {"assigned_id": null, "name": "Kaia Outzen", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCL6JAKDA"}, {"assigned_id": null, "name": "Rory Chambers", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDyjZsKDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgMC1_9EKDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgMC1_9EJDA", "deletable": false}, {"school": "Wayland Middle School", "assigned_id": null, "combinable": true, "name": "Wayland Math Team", "members": [{"assigned_id": null, "name": "Hannah Han", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDOsYAJDA"}, {"assigned_id": null, "name": "Kevin Zhao", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMC13IcKDA"}, {"assigned_id": null, "name": "June Kim", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCigZMKDA"}, {"assigned_id": null, "name": "Andrew Zhao", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMC1xpYKDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgMDOpp4KDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgICumYAKDA", "deletable": false}, {"school": "Doherty Middle School, Andover, MA", "assigned_id": null, "combinable": true, "name": "Doherty Middle School", "members": [{"assigned_id": null, "name": "Christina Li", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgIDOiI0JDA"}, {"assigned_id": null, "name": "Steven Zhang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMD0-oAKDA"}, {"assigned_id": null, "name": "Kaylee Ji", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMD2lokKDA"}, {"assigned_id": null, "name": "Emily Chen", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMC8kZ8KDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgMDct5sKDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgMCInYAKDA", "deletable": false}, {"school": "Jericho, Syosset Middle School", "assigned_id": null, "combinable": true, "name": "Long Island Super", "members": [{"assigned_id": null, "name": "Ethan Zhang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgIC2oIgKDA"}, {"assigned_id": null, "name": "Alex He", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgID394kKDA"}, {"assigned_id": null, "name": "William Hu", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgIDgrJQKDA"}, {"assigned_id": null, "name": "Zhebin Zhao", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMD44psKDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgIDJsYgKDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgMDg64AKDA", "deletable": false}, {"school": "Century Chinese Language School", "assigned_id": null, "combinable": true, "name": "CCLS 2", "members": [{"assigned_id": null, "name": "Eric Zhang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDcnoIJDA"}, {"assigned_id": null, "name": "Sophia Tate", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDc44oJDA"}, {"assigned_id": null, "name": "Audrey Lin", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgICI0YMKDA"}, {"assigned_id": null, "name": "Emma Sun", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgICLoZcKDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgICQx4AKDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgMDcnoIKDA", "deletable": false}, {"school": "Sarah W. Gibbons Middle School", "assigned_id": null, "combinable": true, "name": "Westborough", "members": [{"assigned_id": null, "name": "Ishita Goluguri", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgID14ocKDA"}, "", "", ""], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgMCE85QJDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgMCM6YIKDA", "deletable": false}, {"school": "The Pike School", "assigned_id": null, "combinable": true, "name": "Pike School B", "members": [{"assigned_id": null, "name": "Alexander Lho", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCIlo8JDA"}, {"assigned_id": null, "name": "Stephanie Yang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCqxJoJDA"}, {"assigned_id": null, "name": "Jerry Shu", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgICL-oYKDA"}, {"assigned_id": null, "name": "Chen-chen Song", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCIlo8KDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgICQyY8LDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgMC0pIMKDA", "deletable": false}, {"school": "The Sage School", "assigned_id": null, "combinable": true, "name": "Sage Green", "members": [{"assigned_id": null, "name": "Janani Ganesh", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgIDIo4AJDA"}, {"assigned_id": null, "name": "Aditya Venkatesh", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgID1p4AJDA"}, {"assigned_id": null, "name": "Keep the 3 kids above together!", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgIDuwYwJDA"}, {"assigned_id": null, "name": "Surya Sakhamuri", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCTh4cLDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgMC1_5EKDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgICrzIMKDA", "deletable": false}, {"school": "Affiliated HS to Peking Univ.", "assigned_id": null, "combinable": true, "name": "Beijing 3", "members": [{"assigned_id": null, "name": "Liyuan Liu", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgICujp4KDA"}, {"assigned_id": null, "name": "Zhuoqi Wu", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDC_cQKDA"}, {"assigned_id": null, "name": "Sixue Li", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgIDLkskKDA"}, {"assigned_id": null, "name": "Bati Li", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDVt4sLDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgID1qY8KDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgMDV-YMKDA", "deletable": false}, {"school": "Shibei Middle School", "assigned_id": null, "combinable": true, "name": "Shibei Middle School", "members": [{"assigned_id": null, "name": "Zhefei Cao", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgKCQ-YYKDA"}, {"assigned_id": null, "name": "Yihua Sun", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDzoIoKDA"}, {"assigned_id": null, "name": "Peiqing Chen", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDz1JsKDA"}, {"assigned_id": null, "name": "Meng Sun", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgKCQ7psKDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgIDOnJwJDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgIDO-oMKDA", "deletable": false}, {"school": "Tsinghua University High School and Laurelwood Public School", "assigned_id": null, "combinable": true, "name": "Individual", "members": [{"assigned_id": null, "name": "Zhening Li", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCC7IsKDA"}, "", "", ""], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgMDqrIgKDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgIDcl4QKDA", "deletable": false}, {"school": "Century Chinese Language School", "assigned_id": null, "combinable": true, "name": "CCLS 1", "members": [{"assigned_id": null, "name": "Eric Yang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDk5owJDA"}, {"assigned_id": null, "name": "William Yue", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgIDpnJcJDA"}, {"assigned_id": null, "name": "Andrew W. Lee", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgIDanooKDA"}, {"assigned_id": null, "name": "Jason Tang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgIDa-ZsKDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgICQx4AKDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgMDkmIQKDA", "deletable": false}, {"school": "", "assigned_id": "", "combinable": true, "name": "Michael Cheng (individual)", "members": [{"assigned_id": "", "name": "Michael Cheng", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDyxpMKDA"}, "", "", ""], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgMCezpgKDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgKDQ64UKDA", "deletable": false}, {"school": "Advanced Math and Science Academy Charter School", "assigned_id": null, "combinable": true, "name": "AMSA Red", "members": [{"assigned_id": null, "name": "TBD 2", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCUt4EJDA"}, {"assigned_id": null, "name": "TBD 1", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDwmpwJDA"}, {"assigned_id": null, "name": "TBD 4", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCcgoAKDA"}, {"assigned_id": null, "name": "TBD 3", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDsxYcLDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgMDsxYcKDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgICw7YYKDA", "deletable": false}, {"school": "Gauss School of Mathematics", "assigned_id": null, "combinable": true, "name": "NJAlligators", "members": [{"assigned_id": null, "name": "Bryan Zhang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgIDTt8cIDA"}, {"assigned_id": null, "name": "Christopher Qiu", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgICquIUJDA"}, {"assigned_id": null, "name": "Allan Zhang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCQg4wKDA"}, {"assigned_id": null, "name": "Daniel Zhang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgIDTt8cKDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgIC2oIgJDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgIDTt4cKDA", "deletable": false}, {"school": "Stony Brook Middle School", "assigned_id": null, "combinable": true, "name": "Westford Flying Fish", "members": [{"assigned_id": null, "name": "Max Xu", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgIDLkokKDA"}, "", "", ""], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgMCUioYKDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgIDO34cKDA", "deletable": false}, {"school": "FA Day Middle School", "assigned_id": null, "combinable": true, "name": "Day Two", "members": [{"assigned_id": null, "name": "Ryan Shu", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgIDQpZUJDA"}, {"assigned_id": null, "name": "Jacob Ye", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDMgY4KDA"}, {"assigned_id": null, "name": "David Li", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgIDQpZUKDA"}, {"assigned_id": null, "name": "Thomas Wang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCkj5kKDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgIDqz4ALDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgMCk04gKDA", "deletable": false}, {"school": "Bigelow MS", "assigned_id": null, "combinable": true, "name": "Bigelow Girls", "members": [{"assigned_id": null, "name": "Sophie Murthy", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgKDQ3IEJDA"}, {"assigned_id": null, "name": "Emily Huang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgIDojtsKDA"}, {"assigned_id": null, "name": "Kate Ellison", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDz498KDA"}, {"assigned_id": null, "name": "Helen Xiao", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDyqJ0LDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgIDqz4AKDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgIDVg4kKDA", "deletable": false}, {"school": "Lexington Diamond Middle School", "assigned_id": null, "combinable": true, "name": "Diamond School A", "members": [{"assigned_id": null, "name": "Richard Chen", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDX8MwIDA"}, {"assigned_id": null, "name": "Jeremy Fleming", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgKDkooYJDA"}, {"assigned_id": null, "name": "Bryce Zhang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgKDC14YJDA"}, {"assigned_id": null, "name": "Kristina Wong", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgKDkooYLDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgICO5IEKDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgMC8_4kKDA", "deletable": false}, {"school": "The Sage School", "assigned_id": null, "combinable": true, "name": "Sage Green", "members": [{"assigned_id": null, "name": "Janani Ganesh", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCSpZwJDA"}, {"assigned_id": null, "name": "Aditya Venkatesh", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgIDNuIILDA"}, {"assigned_id": null, "name": "Surya Sakhamuri", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgICe-IoLDA"}, ""], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgMCKsp8KDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgIDN1ooKDA", "deletable": false}, {"school": "Shanghai Foreign Language School", "assigned_id": null, "combinable": true, "name": "SFLS 3", "members": [{"assigned_id": null, "name": "Yiwen Li", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgICt05gJDA"}, {"assigned_id": null, "name": "Jingxian Li", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDuv4EKDA"}, {"assigned_id": null, "name": "Yihong Gu", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCynpkKDA"}, {"assigned_id": null, "name": "Jialin Zuo", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDz1JsLDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgIDOnJwJDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgIDOtYsKDA", "deletable": false}, {"school": "Noble and Greenough School", "assigned_id": null, "combinable": true, "name": "Nobles", "members": [{"assigned_id": null, "name": "Daniel Wang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDTz5kJDA"}, {"assigned_id": null, "name": "Justin Qin", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgIDNuMIJDA"}, {"assigned_id": null, "name": "Lucy Cai", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMD1w8wKDA"}, {"assigned_id": null, "name": "Claire Mao", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCSz9IKDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgIDQs4wKDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgMDx4osKDA", "deletable": false}, {"school": "Gauss School of Mathematics", "assigned_id": null, "combinable": true, "name": "The Superman", "members": [{"assigned_id": null, "name": "Christopher Dong", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgID394kJDA"}, {"assigned_id": null, "name": "Peter Liu", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgICzqJYJDA"}, {"assigned_id": null, "name": "Andrew Zhang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgIDTt8cJDA"}, {"assigned_id": null, "name": "Eric Lin", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgIC2oMgJDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgIC2oIgJDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgIDVpI4KDA", "deletable": false}, {"school": "Jonas Clarke Middle School", "assigned_id": null, "combinable": true, "name": "Clarke B", "members": [{"assigned_id": null, "name": "Euhan Kim", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCX0tEJDA"}, {"assigned_id": null, "name": "Sammy Charney", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgICNr90JDA"}, {"assigned_id": null, "name": "Jeff Lin", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCS04MLDA"}, {"assigned_id": null, "name": "Arthur Hu", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDuhsYLDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgMCEzJAKDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgMCK5I4KDA", "deletable": false}, {"school": "Advanced Math and Science Academy", "assigned_id": null, "combinable": true, "name": "AMSA Blue", "members": [{"assigned_id": null, "name": "Sruthi Kurada", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMC1kY8JDA"}, {"assigned_id": null, "name": "Samuel David", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDxhJIJDA"}, {"assigned_id": null, "name": "Matt Young", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgIDLp40KDA"}, {"assigned_id": null, "name": "Shane Ferrante", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDioo4KDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgIDczpEKDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgMC1kY8KDA", "deletable": false}, {"school": "Affiliated HS to Peking Univ.", "assigned_id": null, "combinable": true, "name": "Beijing 2", "members": [{"assigned_id": null, "name": "Chenui Ji", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgIDO38cIDA"}, {"assigned_id": null, "name": "Jinhui Cao", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgIDI8tYIDA"}, {"assigned_id": null, "name": "Yukun Guan", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgIDLjtgIDA"}, {"assigned_id": null, "name": "Hanlin Gao", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDCp5UJDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgID1qY8KDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgMDCkpEKDA", "deletable": false}, {"school": "Fay school", "assigned_id": null, "combinable": true, "name": "SunShine", "members": [{"assigned_id": null, "name": "Anna", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCi85sKDA"}, "", "", ""], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgICumYALDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgICu_ZEKDA", "deletable": false}, {"school": "Jonas Clarke Middle School", "assigned_id": null, "combinable": true, "name": "Clarke D", "members": [{"assigned_id": null, "name": "Kunal Kapoor", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgIDNnYYKDA"}, {"assigned_id": null, "name": "Aahan Mehra", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDSmIsKDA"}, {"assigned_id": null, "name": "Anna Zhang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgIDN-5cKDA"}, {"assigned_id": null, "name": "Charlie Chen", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgICeh58KDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgMCEzJAKDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgICwgpMKDA", "deletable": false}, {"school": "Raymond J Grey Junior High School", "assigned_id": null, "combinable": true, "name": "RJ Grey", "members": [{"assigned_id": null, "name": "Anuj Sakarda", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDM0JsJDA"}, {"assigned_id": null, "name": "Jerry Tan", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgIC294IKDA"}, {"assigned_id": null, "name": "Poonam Sahoo", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgICa8YQKDA"}, {"assigned_id": null, "name": "Justin Shan", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgICarZUKDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgMCkqp4KDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgIDzspUKDA", "deletable": false}, {"school": "The Pike School", "assigned_id": null, "combinable": true, "name": "Pike School A", "members": [{"assigned_id": null, "name": "Kris Aziabor", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDc1IwKDA"}, {"assigned_id": null, "name": "Arnav Bhakta", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCq6Y8KDA"}, {"assigned_id": null, "name": "Jay Aziabor", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCqjpYKDA"}, {"assigned_id": null, "name": "Adam Jac", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDcip0KDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgICQyY8LDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgMDcwJUKDA", "deletable": false}, {"school": "FA Day Middle School", "assigned_id": null, "combinable": true, "name": "Day One", "members": [{"assigned_id": null, "name": "Charles Li", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDMmpcJDA"}, {"assigned_id": null, "name": "Jason Jiang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgID2vIoKDA"}, {"assigned_id": null, "name": "Eric Yu", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDM5Z8KDA"}, {"assigned_id": null, "name": "Steven Gao", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCk04gLDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgIDqz4ALDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgMCk4JYKDA", "deletable": false}, {"school": "Advanced Math and Science Academy", "assigned_id": null, "combinable": true, "name": "AMSA Gold", "members": [{"assigned_id": null, "name": "Nikhil Rao", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCemYUJDA"}, {"assigned_id": null, "name": "Griffin Coyle", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDz94EKDA"}, {"assigned_id": null, "name": "Nikhita Athipathy", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgIDomYYKDA"}, {"assigned_id": null, "name": "Kazuya Erdos", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCN344KDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgIDczpEKDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgMDiuJcKDA", "deletable": false}, {"school": "Advanced Math and Science Academy Charter School", "assigned_id": null, "combinable": true, "name": "AMSA Gold", "members": [{"assigned_id": null, "name": "TBD 3", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDw_oMKDA"}, {"assigned_id": null, "name": "TBD 4", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDK-o0KDA"}, {"assigned_id": null, "name": "TBD 1", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgIDp4d8KDA"}, {"assigned_id": null, "name": "TBD 2", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDKiIULDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgMDsxYcKDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgMCU7pcKDA", "deletable": false}, {"school": "Beijing No. 4 MS", "assigned_id": null, "combinable": true, "name": "Beijing No. 4 1", "members": [{"assigned_id": null, "name": "Jiahui Zhang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgKCQwIIJDA"}, {"assigned_id": null, "name": "Jiaming Xu", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCzlswKDA"}, {"assigned_id": null, "name": "RUOYI LIU", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCzgtUKDA"}, {"assigned_id": null, "name": "Dingchen Zhang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgICttJ8LDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgID1qY8KDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgIDLjpgKDA", "deletable": false}, {"school": "Timothy Edwards Middle School, South Windsor, CT", "assigned_id": null, "combinable": true, "name": "Pi In The Sky", "members": [{"assigned_id": null, "name": "Ishan Kumar", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMC1kc8IDA"}, {"assigned_id": null, "name": "Aryan Kalia", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDOzdEIDA"}, {"assigned_id": null, "name": "Pranav Ramesh", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgICu54gJDA"}, {"assigned_id": null, "name": "Keshav Ramesh", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDiuJcLDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgICq1o0JDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgIC21JkKDA", "deletable": false}, {"school": "Westchester Area Math Circle", "assigned_id": null, "combinable": true, "name": "Westchester Area Math Circle A", "members": [{"assigned_id": null, "name": "Sam Florin", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgIC2yoQJDA"}, {"assigned_id": null, "name": "Grace Tian", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgIDPw48JDA"}, {"assigned_id": null, "name": "Amy Hu", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgICzm4gKDA"}, {"assigned_id": null, "name": "Erik Brodsky", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgIDq054KDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgMCEmokKDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgIDP8poKDA", "deletable": false}, {"school": "Rj grey JHS, McCall middle school, Blanchard middle school", "assigned_id": null, "combinable": true, "name": "WAW United", "members": [{"assigned_id": null, "name": "Alexander sun", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDI4IgJDA"}, {"assigned_id": null, "name": "Eddie Wang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCMhJUJDA"}, {"assigned_id": null, "name": "William Sun", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCCy48KDA"}, {"assigned_id": null, "name": "Matthew Ding", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgIDOq5oLDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgMCMhJUKDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgMCC-poKDA", "deletable": false}, {"school": "Diamond Middle School", "assigned_id": null, "combinable": true, "name": "It's 5 year old simple", "members": [{"assigned_id": null, "name": "Matt Berhe", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCJ88QIDA"}, {"assigned_id": null, "name": "William Yang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgIDt5twIDA"}, {"assigned_id": null, "name": "Surya Meiyappan", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDzysYJDA"}, {"assigned_id": null, "name": "Jacob Epstein", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgKDQxtAKDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgMDUqJAKDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgMDK4ZwKDA", "deletable": false}, {"school": "Affiliated HS to Peking Univ.", "assigned_id": null, "combinable": true, "name": "Beijing 1", "members": [{"assigned_id": null, "name": "Ze Fan", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgICt4I4JDA"}, {"assigned_id": null, "name": "Tianyi Lu", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDxx48LDA"}, {"assigned_id": null, "name": "Xike Song", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCN7JMLDA"}, {"assigned_id": null, "name": "Yuhan Wang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCJ0J4LDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgID1qY8KDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgMCM9p0KDA", "deletable": false}, {"school": "Advanced Math and Science Academy", "assigned_id": null, "combinable": true, "name": "AMSA Red", "members": [{"assigned_id": null, "name": "Vikram Kaushik", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCa-IIJDA"}, {"assigned_id": null, "name": "Ryan Young", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDiuJcJDA"}, {"assigned_id": null, "name": "Krishna Purimetla", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgIDu2pUKDA"}, {"assigned_id": null, "name": "Sidhant Roymoulik", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgIDIuZ4KDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgIDczpEKDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgMC1jZ4KDA", "deletable": false}, {"school": "The Rectory School", "assigned_id": null, "combinable": true, "name": "Rectory Silver Wolves", "members": [{"assigned_id": null, "name": "Leo Wu", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDuhoYJDA"}, {"assigned_id": null, "name": "Catherine Xie", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCSvo0KDA"}, {"assigned_id": null, "name": "Tina Wang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDTpZEKDA"}, {"assigned_id": null, "name": "Kevin Zhang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDuhoYLDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgMDk25MJDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgMC1_7EKDA", "deletable": false}, {"school": "HS Affiliated to Renmin Univ.", "assigned_id": null, "combinable": true, "name": "Renmin 2", "members": [{"assigned_id": null, "name": "Yichen Xiao", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgICtqsEIDA"}, {"assigned_id": null, "name": "Peiqi Zhang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCzlswIDA"}, {"assigned_id": null, "name": "Zijian Zhang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgICttJ8JDA"}, {"assigned_id": null, "name": "Evan Ai", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCNiIILDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgID1qY8KDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgMCOhcsKDA", "deletable": false}, {"school": "Bergen County Academies", "assigned_id": null, "combinable": true, "name": "Bergen County Academies - Sif", "members": [{"assigned_id": null, "name": "Jooeun Lee", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCL0YUJDA"}, {"assigned_id": null, "name": "Yul Julia Kim", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCLm40KDA"}, {"assigned_id": null, "name": "Sophie Liu", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCLzZQKDA"}, {"assigned_id": null, "name": "Linda Sun", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCN344LDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgICN84wJDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgMCSpdwKDA", "deletable": false}, {"school": "Lexington Youth Center for Asian Learning", "assigned_id": null, "combinable": true, "name": "LYCAL", "members": [{"assigned_id": null, "name": "Eric Teng Tu", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgID1p4AKDA"}, {"assigned_id": null, "name": "Richard Chen", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCTh4cKDA"}, {"assigned_id": null, "name": "Christopher Ye", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgICNzIgKDA"}, {"assigned_id": null, "name": "Ivy Zhang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgICN0JEKDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgICO5IEKDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgICL34ELDA", "deletable": false}, {"school": "Shanghai Foreign Language School", "assigned_id": null, "combinable": true, "name": "SFLS 2", "members": [{"assigned_id": null, "name": "Junkai Wang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCy1JEJDA"}, {"assigned_id": null, "name": "Yurou Liu", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCyyogKDA"}, {"assigned_id": null, "name": "Yuchen Yang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgKCQt44KDA"}, {"assigned_id": null, "name": "Yuhe Huang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCNoZsKDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgIDOnJwJDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgIDO-oMLDA", "deletable": false}, {"school": "Bergen County Academies", "assigned_id": null, "combinable": true, "name": "Bergen County Academies - Tyr", "members": [{"assigned_id": null, "name": "Johnathan Wong", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCe0skIDA"}, {"assigned_id": null, "name": "Katherine Vandermel", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgKCk85MKDA"}, {"assigned_id": null, "name": "Kevin Li", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgKDQjZgLDA"}, {"assigned_id": null, "name": "Debra Boutom", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDakM4LDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgICN84wJDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgICohoQLDA", "deletable": false}, {"school": "Nanjing", "assigned_id": null, "combinable": true, "name": "Nanjing", "members": [{"assigned_id": null, "name": "Wanhe Zhu", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCemYUKDA"}, {"assigned_id": null, "name": "Jiaheng Han", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDy0YoKDA"}, {"assigned_id": null, "name": "Huishen Peng", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgKCwpI0KDA"}, {"assigned_id": null, "name": "Tianyi Lu", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgKDQ_5QKDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgID1qY8KDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgMCO94cLDA", "deletable": false}, {"school": "HS attached to Tsinghua Univ.", "assigned_id": null, "combinable": true, "name": "Tsinghua 1", "members": [{"assigned_id": null, "name": "Xinyi Xiong", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCJ0J4JDA"}, {"assigned_id": null, "name": "Yumeng Wang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDuq58JDA"}, {"assigned_id": null, "name": "Yiran Cao", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCah9cJDA"}, {"assigned_id": null, "name": "Beining Zhou", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCzu5MLDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgID1qY8KDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgIDLkokLDA", "deletable": false}, {"school": "Shanghai Foreign Language School", "assigned_id": null, "combinable": true, "name": "SFLS 1", "members": [{"assigned_id": null, "name": "Jiayi Wang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgKCQ7psJDA"}, {"assigned_id": null, "name": "Hanqing Li", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCN-ooKDA"}, {"assigned_id": null, "name": "Yixiao Huang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCy1JEKDA"}, {"assigned_id": null, "name": "Zhongyu Huang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgKCQo5cKDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgIDOnJwJDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgMC8_4kLDA", "deletable": false}, {"school": "McCall Middle School", "assigned_id": null, "combinable": true, "name": "WinMath", "members": [{"assigned_id": null, "name": "Arthur Zhang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgICoq50JDA"}, {"assigned_id": null, "name": "Kevin Huang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCyoIAKDA"}, {"assigned_id": null, "name": "Mark Sun", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgICov4IKDA"}, {"assigned_id": null, "name": "Arthur Lee", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgKCQiooKDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgMCatooLDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgIDuwYwLDA", "deletable": false}, {"school": "Diamond Middle School", "assigned_id": null, "combinable": true, "name": "Diamond School C", "members": [{"assigned_id": null, "name": "Victoria Yuan", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCxusUIDA"}, {"assigned_id": null, "name": "Julian Han", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMD8w9wIDA"}, {"assigned_id": null, "name": "Brian Yu", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMD85LgKDA"}, {"assigned_id": null, "name": "Matthew Wang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMC8jcEKDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgICO5IEKDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgMCI-5ELDA", "deletable": false}, {"school": "Bergen County Academies", "assigned_id": null, "combinable": true, "name": "Bergen County Academies - Frija", "members": [{"assigned_id": null, "name": "To be determined 2", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDL5IMKDA"}, {"assigned_id": null, "name": "Alexandra Jerdee", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgKDkyY4KDA"}, {"assigned_id": null, "name": "To be determined 1", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgKCi9ZAKDA"}, {"assigned_id": null, "name": "To be determined 3", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDa6oELDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgICN84wJDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgMD12ZULDA", "deletable": false}, {"school": "Bromfield", "assigned_id": null, "combinable": true, "name": "Bromfield", "members": [{"assigned_id": null, "name": "Vivian Liu", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDi1p8JDA"}, {"assigned_id": null, "name": "Jack Yu", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDiyYEKDA"}, {"assigned_id": null, "name": "Olivia Ren", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCulIQKDA"}, {"assigned_id": null, "name": "Tiana Jiang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDOzZELDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgMCugJkKDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgIDu2pULDA", "deletable": false}, {"school": "LexingtonMath", "assigned_id": null, "combinable": true, "name": "Rock Math", "members": [{"assigned_id": null, "name": "Robert Sheng", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgIDNwtMIDA"}, {"assigned_id": null, "name": "Eddie Wei", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDxqYcJDA"}, {"assigned_id": null, "name": "Kevin Guo", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCSz5IJDA"}, {"assigned_id": null, "name": "Jianzhou Liu", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgICohoQKDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgMDuyIoKDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgMCSkJgLDA", "deletable": false}, {"school": "The Sage School", "assigned_id": null, "combinable": true, "name": "Sage Blue", "members": [{"assigned_id": null, "name": "Isaac Lau", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgIDNuIIJDA"}, {"assigned_id": null, "name": "Achyuta Rajaram", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDTs4gKDA"}, {"assigned_id": null, "name": "Oscar Capraro", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCSz5IKDA"}, {"assigned_id": null, "name": "Jacob Greenfield", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgIDNwpMLDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgMCKsp8KDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgICNr50LDA", "deletable": false}, {"school": "HS attached to Tsinghua Univ.", "assigned_id": null, "combinable": true, "name": "Tsinghua 2", "members": [{"assigned_id": null, "name": "Jiangshan Gao", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgICo9cwIDA"}, {"assigned_id": null, "name": "FEIYANG YANG", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCzu5MJDA"}, {"assigned_id": null, "name": "Xinyue Zhang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDSrY8KDA"}, {"assigned_id": null, "name": "Zixi Wang", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMDuq58KDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgID1qY8KDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgMCM9p0LDA", "deletable": false}, {"school": "Boston Latin School", "assigned_id": null, "combinable": true, "name": "dx", "members": [{"assigned_id": null, "name": "Ronak", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgICLiIoJDA"}, {"assigned_id": null, "name": "Eric Cheung", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgICL7JsKDA"}, {"assigned_id": null, "name": "Raymond", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCKw4kLDA"}, {"assigned_id": null, "name": "Ruth Shiferaw", "id": "ag1zfmV4ZXRlci1tYXRochcLEgpJbmRpdmlkdWFsGICAgMCK15gLDA"}], "user": "ag1zfmV4ZXRlci1tYXRochELEgRVc2VyGICAgMCkvoAKDA", "confirmed": true, "id": "ag1zfmV4ZXRlci1tYXRochELEgRUZWFtGICAgIDcpJ4LDA", "deletable": false}]"""

teams = json.loads(teamsstr)
teams2 = json.loads(teams2str)
for i in range(len(teams)):
    team = teams[i]
    name = team['Team name']
    mem1 = team['Member 1']
    mem2 = team['Member 2']
    mem3 = team['Member 3']
    mem4 = team['Member 4']
    teamid = team['Team ID']
    found = False
    for j in range(len(teams2)):
        if(teams2[j]['name'] == name):
            found = True
            teams2[j]['assigned_id'] = teamid
            teams2[j]['members'][0]['name'] = mem1
            teams2[j]['members'][1]['name'] = mem2
            teams2[j]['members'][2]['name'] = mem3
            teams2[j]['members'][3]['name'] = mem4
    if not found:
        print "Could not find team with name "+name

f = open('refactoredteamlist.txt', 'w')
f.write(json.dumps(teams2, sort_keys=True, indent=4, separators=(',', ': ')))
f.close()